a = input("Name of anything? ")
b = input("How many hours away? ")
c = input("What are you driving? ")
d = input("Who are you going with?")
e = input("Another person you are going with ")
f = input("Name something you shouldn't put on a sandwich ")
g = input("Name a fruit ")
h = input("Name a drink ")
i = input("A verb ")
j = input("A noun that you shouldn't rub on your skin ")
k = input("A noun you shouldn't wear ")
l = input("A verb that you shouldn't do to a game ")
m = input("A game that doesn't exist and sounds ridiculous ")
n = input("Name something to count ")
o = input("What are you going to do in the " + a + " Beach ocean" )
p = input("Something irregular to do across the beach ")
q = input("What would you find in the sand ")

print("My family is taking a trip to " + a +" Beach, " + b +" hours away. We are riding in a " + c +" with my " + d +" and " + e +". My parents packed a cooler with " + f +" sandwiches, " + g +", and " + h +". They always " + i +" us to wear " + j +" and a " + k +" so we don't get sunburned. During the drive, we will " + l +" games like " + m +" and ''Count the " + n +".'' I can't wait to get there so I can go " + o +" in the ocean and " + p +" along the beach and collect " + q +" I find in the sand.")